# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios
PEREZ, MICAELA DEL M
1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [11]:
#Crear un arreglo de ceros de longitud 12
array= np.zeros(12)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
#Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
array2 = np.zeros(10)
array2[4] = 10
print(array2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [15]:
#Crear un arreglo que tenga los números del 10 al 49
array3 = np.arange(10,50)
print(array3)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
#Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array4 = np.arange(9)
b=array4.reshape(3, 3)
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
#Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
a5 = np.random.randint(0, 100, 100)
#print(a5.size) #para ver el tamaño
print('Array = ', a5)
print('Media = ', np.mean(a5))
print('Varianza = ', np.var(a5))

Array =  [75 79 79 14 92 10 13  6 62  7 50 82 70 93 89 60 41 69 56 56 56  7 87 71
 15 14 64 28 59 54 68 33 10 38 32 14 29 66 41 81 31 62 49 42 12 60  9 66
 68 18 20 69 20 76 62 95 76 42  0 22 75 72 57 82 42 13 23 57 26 40 12 75
  1 63 86  0 84 99 99 20 97 16 41 23 35 39  4 97 71 83 66 86 95 55  3 53
 90 36 36  2]
Media =  49.23
Varianza =  856.0571000000002


In [28]:
#Calcular la media de un arreglo usando np.sum
a6 = np.random.randint(0, 100, 10)
media = np.sum(a6)/a6.size
print('Media = ', media)

Media =  65.6


In [39]:
#Calcular la varianza de un arreglo usando np.sum y np.mean
a7 = np.random.randint(0, 100, 10)
media = np.sum(a7)/a7.size
varianza = np.sum((a7 - media) ** 2) / a7.size
print(f' Array = {a7} \n Varianza = {round(varianza,2)} ')

 Array = [44 93 90 22 90 37 26 21  1 45] 
 Varianza = 978.49 


In [37]:
#Crear un array de números aleatorios usando np.random.randn.
a8 = np.random.randn(5)
a8

array([-0.38918258,  1.15601231, -1.10862914, -1.01073372, -0.16870443])